### ISSUE TITLE
Where can I find the .config file?

### ISSUE THREAD

**Issue by mondalaci** [pazos/android_kernel_samsung_goyawifi#2]
I have a Galaxy Tab Lite 3 (T110) and I'd like to use an USB microscope with it but the USB video class is not supported by the stock kernel. According to https://droidperception.wordpress.com/dashcam/ I need the following options to be enabled:

CONFIG_VIDEO_DEV=y
CONFIG_VIDEO_V4L2_COMMON=y
CONFIG_VIDEO_MEDIA=y
CONFIG_USB_VIDEO_CLASS=y
CONFIG_V4L_USB_DRIVERS=y
CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV=y

But I don't know whether these options are enabled in your ROM because I can't see the .config file in the root directory.

Could you help, please?

**Comment by vinay94185** [comment]
type make goyawifi_defconfig in terminal in kernel source directory then press CTRL+H to show hidden files then u can see .config.
